"""Init

Revision ID: 4f3e97d81fae
Revises: 9aa5bfe7883c
Create Date: 2023-05-15 10:37:59.910465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3e97d81fae'
down_revision = '9aa5bfe7883c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('contacts', sa.Column('birthday', sa.Date(), nullable=False))
    op.drop_column('contacts', 'birthaday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthaday', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'birthday')
    op.drop_table('users')
    # ### end Alembic commands ###
